# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/MuhammetAliVarlik/AYBU/Vivado_Projects/Interrupt/Interrupt.srcs/sources_1/bd/interrupt/ip/interrupt_xbar_0/interrupt_xbar_0.xci
# IP: The module: 'interrupt_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/MuhammetAliVarlik/AYBU/Vivado_Projects/Interrupt/Interrupt.srcs/sources_1/bd/interrupt/ip/interrupt_xbar_0/interrupt_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'interrupt_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/MuhammetAliVarlik/AYBU/Vivado_Projects/Interrupt/Interrupt.srcs/sources_1/bd/interrupt/ip/interrupt_xbar_0/interrupt_xbar_0.xci
# IP: The module: 'interrupt_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/MuhammetAliVarlik/AYBU/Vivado_Projects/Interrupt/Interrupt.srcs/sources_1/bd/interrupt/ip/interrupt_xbar_0/interrupt_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'interrupt_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
