# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/blink_led/blink_led.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blink_led || ORIG_REF_NAME==blink_led} -quiet] -quiet

# IP: bd/blink_led/ip/blink_led_processing_system7_0_0/blink_led_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blink_led_processing_system7_0_0 || ORIG_REF_NAME==blink_led_processing_system7_0_0} -quiet] -quiet

# IP: bd/blink_led/ip/blink_led_axi_gpio_0_0/blink_led_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blink_led_axi_gpio_0_0 || ORIG_REF_NAME==blink_led_axi_gpio_0_0} -quiet] -quiet

# IP: bd/blink_led/ip/blink_led_auto_pc_0/blink_led_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blink_led_auto_pc_0 || ORIG_REF_NAME==blink_led_auto_pc_0} -quiet] -quiet

# IP: bd/blink_led/ip/blink_led_ps7_0_axi_periph_0/blink_led_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blink_led_ps7_0_axi_periph_0 || ORIG_REF_NAME==blink_led_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/blink_led/ip/blink_led_rst_ps7_0_50M_0/blink_led_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blink_led_rst_ps7_0_50M_0 || ORIG_REF_NAME==blink_led_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: bd/blink_led/blink_led_ooc.xdc
