# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/interrupt/interrupt.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interrupt || ORIG_REF_NAME==interrupt} -quiet] -quiet

# IP: bd/interrupt/ip/interrupt_processing_system7_0_0/interrupt_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interrupt_processing_system7_0_0 || ORIG_REF_NAME==interrupt_processing_system7_0_0} -quiet] -quiet

# IP: bd/interrupt/ip/interrupt_axi_gpio_0_0/interrupt_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interrupt_axi_gpio_0_0 || ORIG_REF_NAME==interrupt_axi_gpio_0_0} -quiet] -quiet

# IP: bd/interrupt/ip/interrupt_axi_gpio_1_0/interrupt_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interrupt_axi_gpio_1_0 || ORIG_REF_NAME==interrupt_axi_gpio_1_0} -quiet] -quiet

# IP: bd/interrupt/ip/interrupt_xbar_0/interrupt_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interrupt_xbar_0 || ORIG_REF_NAME==interrupt_xbar_0} -quiet] -quiet

# IP: bd/interrupt/ip/interrupt_auto_pc_0/interrupt_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interrupt_auto_pc_0 || ORIG_REF_NAME==interrupt_auto_pc_0} -quiet] -quiet

# IP: bd/interrupt/ip/interrupt_ps7_0_axi_periph_0/interrupt_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interrupt_ps7_0_axi_periph_0 || ORIG_REF_NAME==interrupt_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/interrupt/ip/interrupt_rst_ps7_0_50M_0/interrupt_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interrupt_rst_ps7_0_50M_0 || ORIG_REF_NAME==interrupt_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/interrupt/ip/interrupt_axi_timer_0_0/interrupt_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interrupt_axi_timer_0_0 || ORIG_REF_NAME==interrupt_axi_timer_0_0} -quiet] -quiet

# IP: bd/interrupt/ip/interrupt_xlconcat_0_0/interrupt_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interrupt_xlconcat_0_0 || ORIG_REF_NAME==interrupt_xlconcat_0_0} -quiet] -quiet

# XDC: bd/interrupt/interrupt_ooc.xdc
