# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/buttons/buttons.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==buttons || ORIG_REF_NAME==buttons} -quiet] -quiet

# IP: bd/buttons/ip/buttons_processing_system7_0_0/buttons_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==buttons_processing_system7_0_0 || ORIG_REF_NAME==buttons_processing_system7_0_0} -quiet] -quiet

# IP: bd/buttons/ip/buttons_axi_gpio_0_1/buttons_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==buttons_axi_gpio_0_1 || ORIG_REF_NAME==buttons_axi_gpio_0_1} -quiet] -quiet

# IP: bd/buttons/ip/buttons_axi_gpio_1_1/buttons_axi_gpio_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==buttons_axi_gpio_1_1 || ORIG_REF_NAME==buttons_axi_gpio_1_1} -quiet] -quiet

# IP: bd/buttons/ip/buttons_xbar_0/buttons_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==buttons_xbar_0 || ORIG_REF_NAME==buttons_xbar_0} -quiet] -quiet

# IP: bd/buttons/ip/buttons_ps7_0_axi_periph_1/buttons_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==buttons_ps7_0_axi_periph_1 || ORIG_REF_NAME==buttons_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/buttons/ip/buttons_rst_ps7_0_50M_1/buttons_rst_ps7_0_50M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==buttons_rst_ps7_0_50M_1 || ORIG_REF_NAME==buttons_rst_ps7_0_50M_1} -quiet] -quiet

# IP: bd/buttons/ip/buttons_axi_timer_0_0/buttons_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==buttons_axi_timer_0_0 || ORIG_REF_NAME==buttons_axi_timer_0_0} -quiet] -quiet

# IP: bd/buttons/ip/buttons_xlconcat_0_1/buttons_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==buttons_xlconcat_0_1 || ORIG_REF_NAME==buttons_xlconcat_0_1} -quiet] -quiet

# IP: bd/buttons/ip/buttons_auto_pc_0/buttons_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==buttons_auto_pc_0 || ORIG_REF_NAME==buttons_auto_pc_0} -quiet] -quiet

# XDC: bd/buttons/buttons_ooc.xdc
